name: Give the people Squares

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  LOG_LEVEL: WARN

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Restore Rust deps cache
      id: rust-deps-restore
      uses: actions/cache/restore@v4
      with:
        path: ~/.cargo
        key: rust-deps-cache

    - name: Install wasm-pack
      run: cargo install wasm-pack

    - name: Build
      run: wasm-pack build --target=web

    - name: Cache Rust dependencies
      id: cache-rust-deps
      uses: actions/cache/save@v4
      with:
        path: ~/.cargo
        key: rust-deps-cache

    - name: Tar up the package
      id: tar-it-up
      run: tar -czvf pkg.tar.gz pkg index.html

    - name: Upload artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: square_homage
        path: pkg.tar.gz
        if-no-files-found: error

    - name: Deploy this sucker
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: square_homage
